"use client";

import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import { useRouter } from "next/navigation";
import CircleBackground from "@/modules/landing/ui/components/circle-background";
import { Card, CardContent } from "@/components/ui/card";

export default function TermsPage() {
  const router = useRouter();

  return (
    <main className="min-h-screen relative">
      <CircleBackground />
      
      <div className="container mx-auto px-4 py-8 max-w-4xl relative z-10">
        <div className="mb-8">
          <Button 
            variant="ghost" 
            className="gap-2 pl-0 hover:bg-transparent hover:text-primary"
            onClick={() => router.back()}
          >
            <ArrowLeft className="w-4 h-4" />
            Go Back
          </Button>
        </div>

        <Card className="bg-card/80 backdrop-blur-sm border-border/50 shadow-xl">
          <CardContent className="p-8 md:p-12">
            <article className="prose prose-slate dark:prose-invert max-w-none">
              <h1 className="text-4xl font-bold tracking-tight mb-2 bg-clip-text text-transparent bg-gradient-to-r from-foreground to-foreground/70">
                Terms of Service
              </h1>
              <p className="text-muted-foreground mb-8 text-lg">Last updated: December 2, 2025</p>

              <div className="space-y-8 mt-8">
                <section className="space-y-4">
                  <h2 className="text-2xl font-semibold text-foreground">1. Agreement to Terms</h2>
                  <p className="text-muted-foreground leading-relaxed">
                    By accessing or using the services provided by InterviewCrew (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;), 
                    you agree to be bound by these Terms of Service. If you do not agree to these terms, 
                    please do not use our services.
                  </p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-2xl font-semibold text-foreground">2. Description of Services</h2>
                  <p className="text-muted-foreground leading-relaxed">
                    InterviewCrew provides an AI-first technical recruitment platform offering two primary services:
                  </p>
                  <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                    <li>
                      <strong className="text-foreground">For Candidates:</strong> AI-powered career tools including mock interviews, 
                      resume building assistance, and preparation roadmaps. These tools are currently provided free of charge.
                    </li>
                    <li>
                      <strong className="text-foreground">For Clients:</strong> Recruitment services connecting companies with pre-vetted 
                      software engineering talent.
                    </li>
                  </ul>
                </section>

                <section className="space-y-4">
                  <h2 className="text-2xl font-semibold text-foreground">3. AI Technology Disclaimer</h2>
                  <p className="text-muted-foreground leading-relaxed">
                    Our services utilize Artificial Intelligence (AI) technologies, including Large Language Models (LLMs). 
                    By using our services, you acknowledge and agree that:
                  </p>
                  <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                    <li>
                      AI-generated content (including interview feedback, questions, and resume suggestions) 
                      may not always be 100% accurate, complete, or up-to-date.
                    </li>
                    <li>
                      You should verify any critical information or advice generated by our AI tools.
                    </li>
                    <li>
                      We are not liable for decisions made based solely on AI-generated feedback.
                    </li>
                  </ul>
                </section>

                <section className="space-y-4">
                  <h2 className="text-2xl font-semibold text-foreground">4. User Accounts</h2>
                  <p className="text-muted-foreground leading-relaxed">
                    To access certain features, you must create an account. You agree to provide accurate, 
                    current, and complete information during the registration process and to update such 
                    information to keep it accurate, current, and complete. You are responsible for 
                    safeguarding your account credentials.
                  </p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-2xl font-semibold text-foreground">5. Data Usage and Privacy</h2>
                  <p className="text-muted-foreground leading-relaxed">
                    Your use of our services is also governed by our Privacy Policy. By using our services, 
                    you consent to the collection and use of your information as described in our Privacy Policy, 
                    including the use of anonymized data to improve our AI models.
                  </p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-2xl font-semibold text-foreground">6. Intellectual Property</h2>
                  <p className="text-muted-foreground leading-relaxed">
                    The service, including its original content (excluding user-generated content), features, 
                    and functionality, is and will remain the exclusive property of InterviewCrew and its licensors. 
                    Our trademarks may not be used in connection with any product or service without the prior 
                    written consent of InterviewCrew.
                  </p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-2xl font-semibold text-foreground">7. Termination</h2>
                  <p className="text-muted-foreground leading-relaxed">
                    We may terminate or suspend your account and bar access to the Service immediately, 
                    without prior notice or liability, under our sole discretion, for any reason whatsoever 
                    and without limitation, including but not limited to a breach of the Terms.
                  </p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-2xl font-semibold text-foreground">8. Limitation of Liability</h2>
                  <p className="text-muted-foreground leading-relaxed">
                    In no event shall InterviewCrew, nor its directors, employees, partners, agents, suppliers, 
                    or affiliates, be liable for any indirect, incidental, special, consequential or punitive 
                    damages, including without limitation, loss of profits, data, use, goodwill, or other 
                    intangible losses, resulting from your access to or use of or inability to access or use the Service.
                  </p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-2xl font-semibold text-foreground">9. Governing Law</h2>
                  <p className="text-muted-foreground leading-relaxed">
                    These Terms shall be governed and construed in accordance with the laws of Germany, 
                    specifically the state of Hesse, without regard to its conflict of law provisions.
                  </p>
                </section>

                <section className="space-y-4 pt-4 border-t border-border/50">
                  <h2 className="text-2xl font-semibold text-foreground">10. Contact Us</h2>
                  <p className="text-muted-foreground leading-relaxed">
                    If you have any questions about these Terms, please contact us at: {" "}
                    <a href="mailto:sadjad@interviewcrew.io" className="text-primary hover:underline hover:text-primary/80 transition-colors">
                      sadjad@interviewcrew.io
                    </a>
                  </p>
                </section>
              </div>
            </article>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
